version: 2
sphinx:
  configuration: docs/conf.py
formats: all

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install sphinx myst-parser sphinx-rtd-theme sphinx-autodoc2


formats:
  - pdf
  - epub